### ISSUE TITLE
Playlist doesn't fully populate.

### ISSUE THREAD

**Issue by rossird** [scholtes/music-classifier#4]
Make playlist after database has some songs in it. Playlist contains only parts of songs, or is totally missing the song name.

![image](https://cloud.githubusercontent.com/assets/10621484/23581899/327a189c-00ec-11e7-9a45-ab15754d2a12.png)

**Comment by moondc** [comment]
Can I get the full song name for a couple of these occurances?

**Comment by moondc** [comment]
Should work
